services:
  my-service-production:
    container_name: my-service-production
    build:
      target: production
      context: .
      args:
        - PORT=${PORT:-3001}
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          cpus: '0.25'
          memory: '256m'

  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3001}
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
      - '9229:9229'
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          cpus: '0.25'
          memory: '256m'

volumes:
  node_modules:
